### ISSUE TITLE
Crash on Windows 10 when calling fb.insert_channels

### ISSUE THREAD

**Issue by dylanmcdiarmid** [cessen/openexr-rs#20]
Compiles successfully, but can't get a minimal example going. Same result using 0.5.0 and master, stable-1.8 and nightly-1.9, msvc.

I don't know C++ / haven't used openexr before, so it's possible I installed the libraries wrong. I did have to rename all the dlls to append the -2_2 suffix. They are compiled using Windows C++ 2015 Build Tools.

Running the memory_io test through windbg
```
*** WARNING: Unable to verify checksum for C:\thirdparty\vs2015\x64\openexr-2.2.0\deploy\lib\IlmImf-2_2.dll
IlmImf_2_2!std::_Tree<std::_Tmap_traits<Imf_2_2::Name,Imf_2_2::Slice,std::less<Imf_2_2::Name>,std::allocator<std::pair<Imf_2_2::Name const ,Imf_2_2::Slice> >,0> >::_Lbound<Imf_2_2::Name>+0x2d:
00007ffe`7000086d 488b00          mov     rax,qwAord ptr [rax] ds:00000000`00000008=????????????????
0:004> k
 # Child-SP          RetAddr           Call Site
00 0000000d`ba3fe1d0 00007ffe`7000244e IlmImf_2_2!std::_Tree<std::_Tmap_traits<Imf_2_2::Name,Imf_2_2::Slice,std::less<Imf_2_2::Name>,std::allocator<std::pair<Imf_2_2::Name const ,Imf_2_2::Slice> >,0> >::_Lbound<Imf_2_2::Name>+0x2d [c:\program files (x86)\microsoft visual studio\shared\14.0\vc\include\xtree @ 2060]
01 0000000d`ba3fe210 00007ffe`7000098f IlmImf_2_2!std::_Tree<std::_Tmap_traits<Imf_2_2::Name,Imf_2_2::Slice,std::less<Imf_2_2::Name>,std::allocator<std::pair<Imf_2_2::Name const ,Imf_2_2::Slice> >,0> >::lower_bound+0x4e [c:\program files (x86)\microsoft visual studio\shared\14.0\vc\include\xtree @ 1538]
02 0000000d`ba3fe250 00007ffe`7000113c IlmImf_2_2!std::map<Imf_2_2::Name,Imf_2_2::Slice,std::less<Imf_2_2::Name>,std::allocator<std::pair<Imf_2_2::Name const ,Imf_2_2::Slice> > >::_Try_emplace<Imf_2_2::Name>+0x5f [c:\program files (x86)\microsoft visual studio\shared\14.0\vc\include\map @ 209]
03 0000000d`ba3fe370 00007ffe`700014d8 IlmImf_2_2!std::map<Imf_2_2::Name,Imf_2_2::Slice,std::less<Imf_2_2::Name>,std::allocator<std::pair<Imf_2_2::Name const ,Imf_2_2::Slice> > >::try_emplace<>+0x4c [c:\program files (x86)\microsoft visual studio\shared\14.0\vc\include\map @ 244]
04 0000000d`ba3fe3b0 00007ffe`6fffcb1c IlmImf_2_2!std::map<Imf_2_2::Name,Imf_2_2::Slice,std::less<Imf_2_2::Name>,std::allocator<std::pair<Imf_2_2::Name const ,Imf_2_2::Slice> > >::operator[]+0x48 [c:\program files (x86)\microsoft visual studio\shared\14.0\vc\include\map @ 178]
*** WARNING: Unable to verify checksum for memory_io-a1d6b46d4a337528.exe
05 0000000d`ba3fe420 00007ff6`2d80af04 IlmImf_2_2!Imf_2_2::FrameBuffer::insert+0x12c [c:\thirdparty\vs2015\x64\openexr-2.2.0\openexr\ilmimf\imfframebuffer.cpp @ 87]
06 0000000d`ba3fe710 00007ff6`2d79c83a memory_io_a1d6b46d4a337528!CEXR_FrameBuffer_insert+0xc4 [c:\users\dylan\code\openexr-rs\openexr-sys\c_wrapper\cexr.cpp @ 214]
07 0000000d`ba3fe7b0 00007ff6`2d796a6f memory_io_a1d6b46d4a337528!openexr::frame_buffer::FrameBuffer::insert_raw+0x20a [C:\Users\dylan\code\openexr-rs\src\frame_buffer.rs @ 145]
08 0000000d`ba3fe980 00007ff6`2d79890a memory_io_a1d6b46d4a337528!openexr::frame_buffer::FrameBuffer::insert_channels<(f32, f32, f32)>+0x4ff [C:\Users\dylan\code\openexr-rs\src\frame_buffer.rs @ 115]
09 0000000d`ba3fed30 00007ff6`2d7b2c1b memory_io_a1d6b46d4a337528!memory_io::memory_io+0x1da [C:\Users\dylan\code\openexr-rs\tests\memory_io.rs @ 25]
0a 0000000d`ba3ff220 00007ff6`2d7fdbc2 memory_io_a1d6b46d4a337528!test::{{impl}}::call_box<(),closure>+0x1b [C:\projects\rust\src\libtest\lib.rs @ 140]
0b 0000000d`ba3ff260 00007ff6`2d7a1dad memory_io_a1d6b46d4a337528!panic_unwind::__rust_maybe_catch_panic+0x22 [C:\projects\rust\src\libpanic_unwind\lib.rs @ 98]
0c 0000000d`ba3ff2c0 00007ff6`2d7fdbc2 memory_io_a1d6b46d4a337528!std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>+0x1dd [C:\projects\rust\src\libstd\panicking.rs @ 450]
0d 0000000d`ba3ff950 00007ff6`2d7ac15f memory_io_a1d6b46d4a337528!panic_unwind::__rust_maybe_catch_panic+0x22 [C:\projects\rust\src\libpanic_unwind\lib.rs @ 98]
0e 0000000d`ba3ff9b0 00007ff6`2d7fafbf memory_io_a1d6b46d4a337528!alloc::boxed::{{impl}}::call_box<(),closure>+0x12f [C:\projects\rust\src\liballoc\boxed.rs @ 640]
0f 0000000d`ba3ffb60 00007ffe`c5628364 memory_io_a1d6b46d4a337528!std::sys::imp::thread::{{impl}}::new::thread_start+0x7f [C:\projects\rust\src\libstd\sys\windows\thread.rs @ 50]
10 0000000d`ba3ffbc0 00007ffe`c5fc70d1 KERNEL32!BaseThreadInitThunk+0x14
11 0000000d`ba3ffbf0 00000000`00000000 ntdll!RtlUserThreadStart+0x21
```

**Comment by cessen** [comment]
Thanks for the report!  Unfortunately I'm not on Windows.  @Ralith would you be able to look into this?

**Comment by Ralith** [comment]
I'll double-check that our tests pass next time I spin up my Windows environment. I'm not really a Windows guy either, but if it's not a bug on our end, the `std::map` stuff in the backtrace makes me wonder if it's an issue with the OpenEXR libs having been compiled against a different C++ stdlib configuration than the rust binary is being linked against.

> I did have to rename all the dlls to append the -2_2 suffix

You shouldn't need to do this. If the environment variable `OPENEXR_LIB_SUFFIX` is unset, the build script will try to link suffixless versions of the libraries.

**Comment by dylanmcdiarmid** [comment]
I think you are probably right, @Ralith. I've got both 2017 and 2015 build tools installed, so I wouldn't be surprised if there is some issue here. I'm going to close this for now, but I'll reopen if I'm able to verify that isn't the problem.

> You shouldn't need to do this. If the environment variable OPENEXR_LIB_SUFFIX is unset, the build script will try to link suffixless versions of the libraries.

Yes, it may be I set/unset it and some point and didn't refresh properly.

**Comment by dylanmcdiarmid** [comment]
FWIW, I recompiled openexr and zlib with 2017 build tools and got the same error, so definitely check this next time you get a chance. For all I know, I could have some other build tools hiding somewhere that rustup detected and used, but I couldn't figure out how to report which one was/is being used.

**Comment by cessen** [comment]
Reopening.

**Comment by Ralith** [comment]
First, my apologies for the long delay in getting to this.

The test suite passes fine out of the box on master on my windows 10/visual studio build tools 2017/x64 configuration with no special measures taken, so I'm not able to reproduce this.

Are you absolutely certain that you're compiling OpenEXR and zlib with *exactly* the same environment (including C and C++ runtime library) that you're using for rust? For comparison, I built OpenEXR using cmake, in a shell configured by calling vcvars64.bat from my build tools installation, which is the same shell I use for rust development. My cmake flags are `-G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX="$OPENEXR_DIR" -DBUILD_SHARED_LIBS=OFF` and I compile by invoking `cmake --build . --target install --config Release`. Notably, this produces version-suffixed libraries, so you're doing something different.

**Comment by dylanmcdiarmid** [comment]
Thanks for looking into it. I'm pretty sure this is a case of "user doesn't understand how something fundamental works and takes it out on the first library they come across", so I apologize for that. I'll work on getting a simple FFI example working first without OpenEXR, and maybe contribute a setup script with some docs for people coming from a similar background if I can get it working properly on Windows.

The library has been working great for my purposes when running on Linux.
