### ISSUE TITLE
Unresolved import

### ISSUE THREAD

**Issue by dawid-s** [cessen/openexr-rs#23]
Hi there,

First of all, thank you for this wrapper. I am trying to use it following your examples but I am getting:

```
error[E0432]: unresolved import `openexr::Header`
  --> src/main.rs:15:28
   |
15 | use openexr::{FrameBuffer, Header, ScanlineOutputFile, PixelType};
   |                            ^^^^^^ no `Header` in the root

error[E0432]: unresolved import `openexr::ScanlineOutputFile`
  --> src/main.rs:15:36
   |
15 | use openexr::{FrameBuffer, Header, ScanlineOutputFile, PixelType};
   |                                    ^^^^^^^^^^^^^^^^^^ no `ScanlineOutputFile` in the root

```

For some reason it can find FrameBuffer and PixelType though. Any ideas why this is happening would be really appreciated. Thanks!

**Comment by dawid-s** [comment]
Sorry, looks like it was a rookie mistake. My version in Cargo.toml was 0.1.0 instead of 0.5.0.

**Comment by cessen** [comment]
No worries, dawid-s!  Hope you find the crate useful.  If there's any functionality you need that isn't wrapped yet, feel free to file another issue.

**Comment by dawid-s** [comment]
I find it very useful as I am writing yet another educational raytracer so thanks a lot for this :) If I have any requests or comments, I will let you know.
