### ISSUE TITLE
ILMBASE_DIR in Windows

### ISSUE THREAD

**Issue by janispritzkau** [cessen/openexr-rs#24]
What is Ilmbase and how can I get the binaries for it for windows? I can't compile it in windows.

**Comment by Ralith** [comment]
IlmBase is published alongside OpenEXR.

**Comment by cessen** [comment]
More specifically, it's here in the OpenEXR repo: https://github.com/openexr/openexr/tree/develop/IlmBase , and if you go to the main website it's one of the things you can download from the downloads section: http://openexr.com/downloads.html

OpenEXR depends on it, and it's typically treated as part of the OpenEXR release/bundle.
