### ISSUE TITLE
Support multi-threaded I/O

### ISSUE THREAD

**Issue by abusch** [cessen/openexr-rs#25]
First of all, thank you for this crate! I've been using it in my project (https://github.com/abusch/rustracer) with great success. 👍 

I'm not super familiar with OpenEXR but I've noticed it supports multi-threaded I/O by using its own worker thread pool. You configure it by calling `setGlobalThreadCount()`. Would it make sense to expose this function? I tried to give it a shot myself to see if it would work, but somehow I can't compile openexr-rs... I'm getting the following:

```
error[E0433]: failed to resolve. Could not find `Build` in `gcc`
  --> openexr-sys/build.rs:79:24
   |
79 |     let mut gcc = gcc::Build::new();
   |                        ^^^^^ Could not find `Build` in `gcc`
error: aborting due to previous error
error: Could not compile `openexr-sys`.
```

**Comment by cessen** [comment]
Sorry for the delayed response!  Yeah, I think it could make sense to expose that.  My only concern is how it might interact over FFI boundaries, so we'd need to investigate that first.

Your error message also reminds me that we should probably update from the gcc crate to the cc crate that has now supplanted it.  Though I don't think that has anything to do with the failure...?

**Comment by abusch** [comment]
Thanks for the reply. Yeah I forgot to update the ticket but I got around the build issue by running `cargo update`.

I kind of managed to expose the function and it seems to work but I haven't much testing as I quickly realised that this wasn't my bottleneck (PNG loading on the other hand...). I'll try to open a PR with what I've got and do some more testing.

**Comment by cessen** [comment]
Awesome, thanks much!

**Comment by cessen** [comment]
Closing this since the associated PR was abandoned.  If someone wants to tackle this, feel free to re-open!

**Comment by norru** [comment]
Hello, I have hit a huge bottleneck as by default I/O is single threaded and loading from multiple EXRs at once is serialized.

I am not able to reopen the issue.

**Comment by norru** [comment]
Is anybody maintaining this? Last commit is from 2018.

**Comment by cessen** [comment]
Not maintained, I don't believe.  But I'd be really happy to get this in, it's just that the PR seemed abandoned by the author.  If you want to tackle this, please go right ahead!

**Comment by abusch** [comment]
Sorry for falling off the face of the Earth and abandoning this (something something life something kids...). Happy to see someone picking it up! :+1:
