### ISSUE TITLE
Can't compile on macOS (zlib issue)

### ISSUE THREAD

**Issue by bryab** [cessen/openexr-rs#32]
I am attempting to build on macOS 10.14.4.  I get this:

`error: could not find native static library `zlibstatic`, perhaps an -L flag is missing?`

I seem to be unable to make it happy about zlib, trying both the system zlib and zlib installed through homebrew.  It seems to be looking for `zlibstatic`, not sure if there is a naming issue here.

OpenEXR and ILMbase seem to be working fine.

**Comment by cessen** [comment]
Thanks for reporting your issue!

Have you tried setting the `ZLIB_DIR` environment variable that the openexr-rs build uses?

If you already have, and it's still failing, can you find zlib on your system and let me know what library files there are for it?

Unfortunately, I don't have an Apple computer to test on, so I'll need your help to get this sorted out.

**Comment by bryab** [comment]
The below are the system zlib
```
/usr/lib/libz.dylib
/usr/lib/libz.1.2.11.dylib
/usr/lib/libz.1.2.8.dylib
/usr/lib/libz.1.2.5.dylib
/usr/lib/libz.1.dylib
/usr/lib/libz.1.1.3.dylib

/usr/include/zlib.h
```

The below are zlib installed using homebrew

```
/usr/local/opt/zlib//lib/libz.dylib
/usr/local/opt/zlib//lib/pkgconfig
/usr/local/opt/zlib//lib/pkgconfig/zlib.pc
/usr/local/opt/zlib//lib/libz.1.2.11.dylib
/usr/local/opt/zlib//lib/libz.a
/usr/local/opt/zlib//lib/libz.1.dylib

/usr/local/opt/zlib//include/zlib.h
/usr/local/opt/zlib//include/zconf.h
```

I have tried `ZLIB_DIR` in many ways, including pointing it to a zlib that i compiled from source.  I'm sure I'm missing something basic here.  I have also tried manually changing "zlibstatic" in your build script to "libz" and that made Rust happy, but once it got to gcc, it failed.

My environment variables are setup like this (attempting to use zlib from homebrew)

`OPENEXR_DIR=/usr/local ILMBASE_DIR=/usr/local ZLIB_DIR=/usr/local/opt/zlib`

**Comment by cessen** [comment]
Hmm... honestly, I'm pretty stumped then. :-/

@Ralith Do you have a MacOS system you could check this out with?

**Comment by Ralith** [comment]
I do not. You'd probably want to set the lib name to "z", not "libz", or just use pkg-config.

**Comment by cessen** [comment]
@Ralith 
Okay, thanks!

@bryab 
Since neither me nor Ralith have MacOS systems to test on, I think we'll be of limited help.  Give Ralith's suggestions a try if you can, and if it works, let us know!  If not, then if you have the time to do a more thorough investigation yourself that would be *amazing*, but no obligation of course.  If you do figure out the issue, I will happily accept a pull request that fixes things on MacOS.

I'll leave this issue open until we have a fix.

**Comment by bryab** [comment]
Thanks a bunch for looking at this.  I will put some time into it when I can.

**Comment by bryab** [comment]
This was fixed by installing `pkg-config` via homebrew.

I will add that I was incorrect to use openexr via homebrew.  I had to build it statically from source, and set `OPENEXR_LIB_SUFFIX` to `2_3_s`.
